[package]
name = "class_group"
version = "0.4.4"
authors = ["omershlo <omer.shlomovits@gmail.com>"]
edition = "2018"
links = "libpari"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.50"

[dependencies]
libc = "0.2.0"
paillier = { git = "https://github.com/ansonhwa/anson-rust-paillier", tag = "v0.3.4"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.curv]
git = "https://github.com/ansonhwa/curv"
features =  ["ec_secp256k1"]
tag = "v1.0"

